# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.CharField(max_length=15, verbose_name='Fecha del despido:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('workplace', models.CharField(max_length=70, verbose_name='Lugar donde trabajaba:')),
                ('comment', models.CharField(max_length=140, verbose_name='Comentario:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
